"""user migrate

Revision ID: 38e4ae76378b
Revises: acd5f325d4e7
Create Date: 2019-04-14 17:27:18.271469

"""

# revision identifiers, used by Alembic.
revision = '38e4ae76378b'
down_revision = 'acd5f325d4e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'age')
    # ### end Alembic commands ###
