"""user add mobile

Revision ID: bd6d352ebd89
Revises: 38e4ae76378b
Create Date: 2019-04-14 17:43:07.163743

"""

# revision identifiers, used by Alembic.
revision = 'bd6d352ebd89'
down_revision = '38e4ae76378b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('mobile', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_t_user_mobile'), 't_user', ['mobile'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_user_mobile'), table_name='t_user')
    op.drop_column('t_user', 'mobile')
    # ### end Alembic commands ###
