"""empty message

Revision ID: fe7de99e910c
Revises: None
Create Date: 2019-04-14 13:50:33.492638

"""

# revision identifiers, used by Alembic.
revision = 'fe7de99e910c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_user')
    op.drop_table('migrate_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migrate_version',
    sa.Column('repository_id', sa.VARCHAR(length=250), nullable=False),
    sa.Column('repository_path', sa.TEXT(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('repository_id')
    )
    op.create_table('t_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=256), nullable=True),
    sa.Column('email', sa.VARCHAR(length=256), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=512), nullable=True)
    )
    # ### end Alembic commands ###
