### 测试
POST http://{{base-url}}/chain/invoke
token: {{token}}
Content-Type: application/json

{
  "input": {
      "language": "Korean",
      "text": "我的英文成绩很糟糕"
  }
}

### gemini测试
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
X-goog-api-key: AIzaSyAr-umcpUPFa1PROADVqtt5rR-_3DaMdik
Content-Type: application/json

{
    "contents": [
      {
        "parts": [
          {
            "text": "Explain how AI works in a few words"
          }
        ]
      }
    ]
  }